### ISSUE TITLE
Doesn't work.

### ISSUE THREAD

**Issue by Floccinaucinihilipilification11** [rafaga12/after-dark-settings#2]
Your code only works on a machine that already has the After Dark registry keys for each module, otherwise it will crash if you select a module with a missing registry key. Remove your registry keys for the modules and test the settings for each module in your code.

**Comment by rafaga12** [comment]
Hi @Floccinaucinihilipilification11, thanks for your report, effectively, module keys must be already there, i will change that in a future version, for now, if you enable Random, apply the changes and then disable it, the keys must be created.

**Comment by rafaga12** [comment]
This error has been fixed in v2. Thanks!
